### ISSUE TITLE
"out" and "include" folders should not be committed

### ISSUE THREAD

**Issue by osyrisrblx** [ShouxTech/roblox-knit-demo#1]
Hi, this is a really cool demo!

Just wanted to mention that the `out` and `include` folders in `AppleCaptureTS` should be deleted and added to `.gitignore`.
These are generated files, so there's no need to commit them. Users should download and then compile your project using their local copy of the roblox-ts compiler.

**Comment by ShouxTech** [comment]
Thank you for the feedback/help! Glad you found this cool. I have removed the out and include folders in AppleCaptureTS.

**Comment by osyrisrblx** [comment]
Don't forget to add `.gitignore` 😄
